name: Lint Commit Messages

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          
      - name: Create commitlint config
        run: |
          echo '{"extends": ["@commitlint/config-conventional"]}' > .commitlintrc.json
          
      - name: Validate current commit (single commit)
        if: github.event_name == 'push'
        run: echo "${{ github.event.head_commit.message }}" | commitlint
        
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
