name: Test

on: push

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10.5'
        cache: 'pipenv'
        cache-dependency-path: Pipfile.lock
    - name: Install pipenv
      run: pipx install pipenv
    - name: Install dependencies
      run: pipenv sync --dev
    - name: Run tests
      run: pipenv run python -m pytest
