name: Test

on: push

jobs:
  transform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.5'
          cache: 'pipenv'
          cache-dependency-path: Pipfile.lock
          
      - name: Install pipenv
        run: |
          pip install pipenv
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: pipenv sync --dev
        
      - name: Run tests
        run: pipenv run python -m pytest